"""Execute this file with the current directory set to its containing dir.

Note that not all possible configuration values are present in this
autogenerated file.

All configuration values have a default; values that are commented out
serve to show the default.
"""

import logging
import shutil
from pathlib import Path

import alabaster

from src import package

# set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


# copy the examples directory to the docs/_examples directory
def copy_examples() -> None:
    """Copy example notebooks from top-level examples/ to docs/src/_examples/."""
    docs_dir = Path(__file__).parent  # docs/source/
    repo_root = docs_dir.parent.parent  # repo root
    source_examples_dir = repo_root / "examples"
    dest_examples_dir = docs_dir / "_examples"

    # stop moving if the destination directory already exists
    if dest_examples_dir.exists():
        return

    # create the destination directory
    dest_examples_dir.mkdir(exist_ok=True)

    # copy all files from source examples to destination
    if source_examples_dir.exists():
        for item in source_examples_dir.iterdir():
            if item.is_file():
                shutil.copy2(item, dest_examples_dir)
                logger.debug("Copied %s to %s", item.name, dest_examples_dir)
            elif item.is_dir():
                shutil.copytree(item, dest_examples_dir / item.name)
                logger.debug(
                    "Copied directory %s to %s", item.name, dest_examples_dir,
                )
    else:
        logger.warning("Source examples directory %s does not exist",
                       source_examples_dir)


def setup(app) -> None:
    """Sphinx setup hook to copy examples before building."""
    copy_examples()


__version__ = package.__version__

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinxcontrib.jquery",
    "sphinx.ext.autosectionlabel",
    "sphinx_inline_tabs",
    "sphinx_design",
    "sphinx_immaterial",
    "myst_parser",
    "nbsphinx",
]

source_suffix = [".md"]
master_doc = "index"

# General information about the project.
project = "package"
copyright = "The package authors"  # noqa: A001
version = ".".join(__version__.split(".")[:2])
release = __version__

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output ---------------------------------------------------
table_styling_embed_css = False
html_theme_path = [alabaster.get_path(), "../themes"]
extensions += ["alabaster"]
html_theme = "sphinx_immaterial"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "palette": {"scheme": "default"},
    "features": [
        "header.autohide",
        "toc.follow",
        "navigation.path",
        "navigation.instant",
        "navigation.top",
        "navigation.tabs",
        "navigation.tabs.sticky",
        "navigation.tracking",
        "navigation.expand",
        "search.highlight",
        "search.share",
        "content.tabs.link",
        "announce.dismiss",
    ],
    "toc_title": "On this page",
    "repo_url": "https://github.com/cvxpy/cvxpy/",
    "repo_name": "cvxpy",
    "icon": {
        "repo": "fontawesome/brands/github",
    },
    "social": [
        {
            "icon": "fontawesome/brands/github",
            "link": "https://github.com/cvxpy/cvxpy/",
            "name": "Source on github.com",
        },
        {
            "icon": "fontawesome/brands/python",
            "link": "https://github.com/cvxpy/cvxpy/",
        },
    ],
}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/cvxlogo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "css/styling.css",
    "https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css",
]
html_js_files = [
    "https://cdn.datatables.net/2.1.8/js/dataTables.js",
]

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True
