# .github/workflows/doc_deploy.yml
name: doc_deploy

on:
  push:
    branches: [ main ]         # auto-rebuild when docs or code change
    paths:
      - 'docs/**'
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_dispatch:           # still allow manual runs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  doc_deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0       # needed if you e.g. show git commit refs in docs

      - uses: astral-sh/setup-uv@v4
        with:
          version: latest
          python-version: 3.12

      - name: Install deps and build Sphinx docs
        run: |
          uv sync --group doc
          uv run sphinx-build -W --keep-going -b html docs/src docs/_build/html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
